import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Plus, Minus, HelpCircle } from "lucide-react";

interface FAQItemProps {
  key?: React.Key | number;
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}

function FAQItem({ question, answer, isOpen, onToggle }: FAQItemProps) {
  return (
    <div className="border-b border-neutral-200/60 py-4 last:border-none">
      <button
        onClick={onToggle}
        className="flex w-full items-center justify-between text-left py-2 font-sans focus:outline-none cursor-pointer group"
      >
        <span className="text-base sm:text-lg font-bold text-neutral-800 group-hover:text-black transition-colors">
          {question}
        </span>
        <div className={`w-8 h-8 rounded-full border border-neutral-200 flex items-center justify-center transition-all ${
          isOpen ? "bg-black text-white border-black" : "bg-neutral-50 text-neutral-400 group-hover:border-neutral-300"
        }`}>
          {isOpen ? <Minus className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
        </div>
      </button>

      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <p className="text-sm sm:text-base text-neutral-500 leading-relaxed pt-2 pb-4 font-normal max-w-4xl">
              {answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: "What exactly is Evion AI and how does it help me?",
      answer: "Evion AI is India's first complete, AI-powered career companion engineered specifically for engineering students preparing for placements. We package ATS resume compilers, voice-synthesized face-tracking interview simulators, DSA drills, and digital portfolio hosting into one unified, elegant dashboard.",
    },
    {
      question: "How does the AI Mock Interview facial and speech analysis work?",
      answer: "When you start the simulator, your browser camera evaluates baseline eye-contact angles and micro-expressions, while your microphone measures response delays and speech pitch patterns. These parameters are translated locally into a performance report with zero video/audio files ever uploaded to any server, keeping your data 100% private.",
    },
    {
      question: "Are the resumes generated by Evion actually ATS-compliant?",
      answer: "Yes, completely. Traditional MS Word templates fail modern Applicant Tracking Systems (ATS) because of bad column formatting, icons, and non-standard tables. Evion compiles your resume into clean, single-column JSON-structured files styled in typography that parses perfectly with zero errors across major corporate recruitment portals like Workday and Taleo.",
    },
    {
      question: "Can colleges buy bulk licenses for their placement departments?",
      answer: "Absolutely. Our Enterprise tier offers white-labeled portals, campus-wide placement stats, dedicated placement officer admin panels, and LMS integrations. Your training staff can review customized bulk interview scorecards of entire classes in one click. Contact us to schedule a campus demonstration.",
    },
    {
      question: "When is the official nationwide launch?",
      answer: "We are currently running a private beta with selected students from NITs and VIT. The public nationwide launch of the platform is scheduled for Q3 2026. By joining the waitlist today, you will receive premium beta invites and a lifetime 30% discount on all Pro plans.",
    },
  ];

  return (
    <section id="faq" className="py-20 md:py-32 bg-[#FAFAFA] border-b border-neutral-200/50">
      <div className="w-[92%] max-w-4xl mx-auto">
        
        {/* Header Section */}
        <div className="text-center mb-16 md:mb-24">
          <span className="text-xs font-mono font-bold uppercase tracking-widest text-accent mb-3 block">
            COMMON INQUIRIES
          </span>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight text-black mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-sm sm:text-base text-neutral-500 max-w-md mx-auto">
            Everything you need to know about Evion AI, our security protocols, and roadmap plans.
          </p>
        </div>

        {/* FAQ List */}
        <div className="glass-card bg-white/50 border-white/50 rounded-[32px] p-6 sm:p-10 shadow-lg">
          {faqs.map((faq, idx) => (
            <FAQItem
              key={idx}
              question={faq.question}
              answer={faq.answer}
              isOpen={openIndex === idx}
              onToggle={() => setOpenIndex(openIndex === idx ? null : idx)}
            />
          ))}
        </div>

      </div>
    </section>
  );
}
